ARG: {category: target, dims: 46, size: 46, type: choice}
CHUNK_CANDIDATE_ID: {category: feature, dims: null, size: 1, type: int}
CHUNK_FINISH: {category: feature, dims: null, size: 1, type: int}
CHUNK_ID: {category: feature, dims: null, size: 1, type: int}
CHUNK_LEN: {category: feature, dims: null, size: 1, type: int}
CHUNK_START: {category: feature, dims: null, size: 1, type: int}
CTREE: {category: feature, dims: 996, size: 996, type: choice}
FORM: {category: feature, dims: 43441, size: 50, type: text}
FORM_CTX_P+0: {category: feature, dims: 43441, size: 50, type: text}
FORM_CTX_P+1: {category: feature, dims: 43441, size: 50, type: text}
FORM_CTX_P+2: {category: feature, dims: 43441, size: 50, type: text}
FORM_CTX_P+3: {category: feature, dims: 43441, size: 50, type: text}
FORM_CTX_P-1: {category: feature, dims: 43441, size: 50, type: text}
FORM_CTX_P-2: {category: feature, dims: 43441, size: 50, type: text}
FORM_CTX_P-3: {category: feature, dims: 43441, size: 50, type: text}
GPOS: {category: feature, dims: 48, size: 48, type: choice}
GPOS_CTX_P+0: {category: feature, dims: 48, size: 48, type: choice}
GPOS_CTX_P+1: {category: feature, dims: 48, size: 48, type: choice}
GPOS_CTX_P+2: {category: feature, dims: 48, size: 48, type: choice}
GPOS_CTX_P+3: {category: feature, dims: 48, size: 48, type: choice}
GPOS_CTX_P-1: {category: feature, dims: 48, size: 48, type: choice}
GPOS_CTX_P-2: {category: feature, dims: 48, size: 48, type: choice}
GPOS_CTX_P-3: {category: feature, dims: 48, size: 48, type: choice}
ID: {category: feature, dims: null, size: 1, type: int}
INDEX: {category: meta, dims: null, size: 1, type: int}
IOB: {category: target, dims: 47, size: 47, type: choice}
MARKER: {category: feature, dims: null, size: 1, type: int}
P: {category: meta, dims: null, size: 1, type: int}
PRED: {category: feature, dims: 3136, size: 50, type: text}
P_S: {category: meta, dims: null, size: 1, type: int}
R: {category: target, dims: 3, size: 3, type: choice}
S: {category: meta, dims: null, size: 1, type: int}
SHALLOW_CHUNKS: {category: feature, dims: 12, size: 12, type: choice}
T: {category: target, dims: 24, size: 24, type: choice}
