ARG: {category: target, dims: 37, size: 37, type: choice}
CHUNK_CANDIDATE_ID: {category: feature, dims: null, size: 1, type: int}
CHUNK_FINISH: {category: feature, dims: null, size: 1, type: int}
CHUNK_ID: {category: feature, dims: null, size: 1, type: int}
CHUNK_LEN: {category: feature, dims: null, size: 1, type: int}
CHUNK_START: {category: feature, dims: null, size: 1, type: int}
CTREE: {category: feature, dims: 310, size: 310, type: choice}
FORM: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P+0: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P+1: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P+2: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P+3: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P-1: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P-2: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P-3: {category: feature, dims: 13207, size: 1, type: text}
GPOS: {category: feature, dims: 26, size: 26, type: choice}
GPOS_CTX_P+0: {category: feature, dims: 26, size: 26, type: choice}
GPOS_CTX_P+1: {category: feature, dims: 26, size: 26, type: choice}
GPOS_CTX_P+2: {category: feature, dims: 26, size: 26, type: choice}
GPOS_CTX_P+3: {category: feature, dims: 26, size: 26, type: choice}
GPOS_CTX_P-1: {category: feature, dims: 26, size: 26, type: choice}
GPOS_CTX_P-2: {category: feature, dims: 26, size: 26, type: choice}
GPOS_CTX_P-3: {category: feature, dims: 26, size: 26, type: choice}
ID: {category: feature, dims: null, size: 1, type: int}
INDEX: {category: meta, dims: null, size: 1, type: int}
IOB: {category: target, dims: 37, size: 37, type: choice}
LEMMA: {category: feature, dims: 9006, size: 1, type: text}
LEMMA_CTX_P+0: {category: feature, dims: 9006, size: 1, type: text}
LEMMA_CTX_P+1: {category: feature, dims: 9006, size: 1, type: text}
LEMMA_CTX_P+2: {category: feature, dims: 9006, size: 1, type: text}
LEMMA_CTX_P+3: {category: feature, dims: 9006, size: 1, type: text}
LEMMA_CTX_P-1: {category: feature, dims: 9006, size: 1, type: text}
LEMMA_CTX_P-2: {category: feature, dims: 9006, size: 1, type: text}
LEMMA_CTX_P-3: {category: feature, dims: 9006, size: 1, type: text}
MARKER: {category: feature, dims: null, size: 1, type: int}
MORF: {category: feature, dims: 113, size: 113, type: choice}
P: {category: meta, dims: null, size: 1, type: int}
PRED: {category: feature, dims: 1025, size: 1, type: text}
P_S: {category: meta, dims: null, size: 1, type: int}
R: {category: target, dims: 3, size: 3, type: choice}
S: {category: meta, dims: null, size: 1, type: int}
SHALLOW_CHUNKS: {category: feature, dims: 12, size: 12, type: choice}
T: {category: target, dims: 19, size: 19, type: choice}
