ARG: {category: target, dims: 37, size: 1, type: choice}
FORM: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P+0: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P+1: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P+2: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P+3: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P-1: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P-2: {category: feature, dims: 13207, size: 1, type: text}
FORM_CTX_P-3: {category: feature, dims: 13207, size: 1, type: text}
GPOS: {category: feature, dims: 26, size: 1, type: choice}
ID: {category: feature, dims: null, size: 1, type: int}
INDEX: {category: meta, dims: null, size: 1, type: int}
IOB: {category: target, dims: 37, size: 1, type: choice}
MARKER: {category: feature, dims: null, size: 1, type: int}
P: {category: meta, dims: null, size: 1, type: int}
PRED: {category: feature, dims: 1025, size: 1, type: text}
R: {category: target, dims: 3, size: 1, type: choice}
SHALLOW_CHUNKS: {category: feature, dims: 12, size: 1, type: choice}
T: {category: target, dims: 19, size: 1, type: choice}
